server:
  port: ${PORT}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      cluster:
        nodes:
      host: localhost
      mode: standalone
      password:
      port: 6379
      ssl:
        enabled: false
      username:
  flyway:
    url: jdbc:mysql://localhost:3306/${DATASOURCE_NAME}
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
