app:
  response:
    include-metadata: true
logging:
  level:
    root: INFO
spring:
  data:
    redis:
      cluster:
        nodes:
      host: localhost
      mode: standalone
      password:
      port: 6379
      ssl:
        enabled: false
      username:
  profiles:
    active: ${ENV} # update ENV to local for local run
  config:
    import: optional:secrets.yml
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
    out-of-order: true
    url: ${DATASOURCE_URL}:${DATASOURCE_NAME}
